config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :tasks, :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(tasks_params)
    if @task.save
      flash[:notice] = 'Task was successfully created.'
      redirect_to @task
    else
      render 'new'
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(tasks_params)
      flash[:notice] = 'Task was successfully edited.'
      redirect_to @task
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def tasks_params
    params.require(:task).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(users_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete
    redirect_to users_path
  end

  private

  def users_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskmanager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% flash.each do |key, message| %>
  <p class="<%= key %>"><%= message %></p>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with model: @task, local: true do |form| %>
  <% if @task.errors.any? %>
    <h2><%= pluralize(@task.errors.count, 'error')%> Prohibited this task from being saved:</h2>
    <ul>
    <% @task.errors.full_messages.each do |msg|%>
      <li> <%= msg %></li>  
    <% end %>
    </ul>
  <% end %>
  <p>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.submit %><br>
  </p>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>All tasks</h1>
<%= link_to 'New Task', new_task_path(@task) %>
<table>
  <tr>
    <th>Title</th>
    <th></th>
  </tr>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %><td>
      <td><%= link_to 'show', task_path(task) %><td>
      <td><%= link_to 'edit', edit_task_path(task) %><td>
      <td><%= link_to 'delete', task_path(task),
              method: :delete,
              data: {confirm: 'Are you sure?'}%><td>
    </tr>
  <% end %>
  </tr>
</table>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<h1>Task</h1>
<p>
  <%= render 'shared/flashes' %>
</p>
<p>
  <strong>Title:</strong> 
  <%= @task.title %>
</p>

<%= link_to 'Edit', edit_task_path %>
<%= link_to 'Delete', task_path,
              method: :delete,
              data: {confirm: 'Are you sure?'}%><br>
<%= link_to 'All Tasks', tasks_path %>
 

app/views/users/_form.html.erb
<%= form_with model: @user, local: true  do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to 'New User', new_user_path(@user) %>
<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %><td>
      <td><%= link_to 'show', user_path(user) %><td>
      <td><%= link_to 'edit', edit_user_path(user) %><td>
      <td><%= link_to 'delete', user_path(user),
              method: :delete,
              data: {confirm: 'Are you sure?'}%><td>
    </tr>
  <% end %>
  </tr>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>User</h1>

<p>
  <strong>Name</strong>
  <%= @user.name %>
</p>

<%= link_to 'All Users', users_path %>
<%= link_to 'Edit User', edit_user_path%>

app/views/welcome/index.html.erb
<h1>Welcome on my site</h1>
<p>Task manager</p>

<%= link_to 'Tasks', tasks_path%>
<%= link_to 'Users', users_path%>